#!/usr/bin/env python3
"""Rasterize Micro5 into deterministic 1-bit deck numerals."""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts" / "audition"
OUT = ROOT / "main" / "micro5_digits.h"
PREVIEW = ROOT / "assets" / "fonts" / "micro5-preview.png"
WIDTH, HEIGHT = 20, 28
STRIDE = (WIDTH + 7) // 8

# name, file, starting pixel size, optional variable-axis values
SPECS = [("Micro5", "Micro5-Regular.ttf", 58, None)]


def load_font(path, size, axes):
    font = ImageFont.truetype(str(path), size)
    if axes:
        font.set_variation_by_axes(axes)
    return font


def glyph_image(path, start_size, axes, glyph):
    # Keep the source at an integer native size. We step the font down until it
    # fits instead of resizing a rendered glyph, which preserves its pixel grid.
    for size in range(start_size, 7, -1):
        font = load_font(path, size, axes)
        probe = Image.new("L", (96, 96), 0)
        draw = ImageDraw.Draw(probe)
        box = draw.textbbox((0, 0), glyph, font=font)
        draw.text((-box[0], -box[1]), glyph, font=font, fill=255)
        crop = probe.getbbox()
        if not crop:
            continue
        source = probe.crop(crop)
        if source.width <= WIDTH and source.height <= HEIGHT:
            # A hard threshold is intentional: the LCD gets designed 1-bit
            # contours, not antialiased TTF fringes.
            source = source.point(lambda p: 255 if p >= 128 else 0).convert("1")
            target = Image.new("1", (WIDTH, HEIGHT), 0)
            target.paste(source, ((WIDTH - source.width) // 2, HEIGHT - source.height))
            return target
    raise RuntimeError(f"could not fit {path.name} {glyph}")


variants = []
bounds = []
GLYPHS = "1234560789"  # preserve the six deck-slot indices
preview = Image.new("RGB", (len(GLYPHS) * 34, len(SPECS) * 42), "#f1f0eb")
preview_draw = ImageDraw.Draw(preview)

for row, (name, filename, size, axes) in enumerate(SPECS):
    path = FONT_DIR / filename
    if not path.exists():
        raise SystemExit(f"missing {path}")
    packed_glyphs, glyph_bounds = [], []
    for col, glyph in enumerate(GLYPHS):
        image = glyph_image(path, size, axes, glyph)
        left, top, right, bottom = image.getbbox()
        glyph_bounds.append((left, top, right - left, bottom - top))
        packed = []
        for y in range(HEIGHT):
            for x0 in range(0, WIDTH, 8):
                byte = 0
                for bit in range(8):
                    if x0 + bit < WIDTH and image.getpixel((x0 + bit, y)):
                        byte |= 1 << (7 - bit)
                packed.append(byte)
        packed_glyphs.append(packed)
        tile = image.convert("L").resize((30, 42), Image.Resampling.NEAREST)
        preview.paste(Image.merge("RGB", (tile, tile, tile)), (col * 34 + 4, row * 42))
    variants.append(packed_glyphs)
    bounds.append(glyph_bounds)
    preview_draw.text((1, row * 42), str(row + 1), fill="#3050d8")

lines = [
    "// Generated by tools/generate_micro5_digits.py; source is OFL-1.1.",
    "#pragma once",
    "#include <cstdint>",
    "namespace micro5_digits {",
    f"constexpr int kCount = {len(SPECS)};",
    f"constexpr int kWidth = {WIDTH};",
    f"constexpr int kHeight = {HEIGHT};",
    f"constexpr int kStride = {STRIDE};",
    "constexpr const char* kNames[kCount] = {" + ", ".join(f'\"{s[0]}\"' for s in SPECS) + "};",
]
for field, pos in (("Left", 0), ("Top", 1), ("VisualWidth", 2), ("VisualHeight", 3)):
    lines.append(f"constexpr int k{field}[kCount][{len(GLYPHS)}] = {{")
    for variant in bounds:
        lines.append("    {" + ", ".join(str(g[pos]) for g in variant) + "},")
    lines.append("};")
lines.append(f"constexpr uint8_t kGlyphs[kCount][{len(GLYPHS)}][{HEIGHT * STRIDE}] = {{")
for variant in variants:
    lines.append("    {")
    for data in variant:
        lines.append("        {")
        for start in range(0, len(data), 16):
            lines.append("            " + ", ".join(f"0x{x:02x}" for x in data[start:start + 16]) + ",")
        lines.append("        },")
    lines.append("    },")
lines.extend(["};", "}  // namespace micro5_digits", ""])

OUT.write_text("\n".join(lines))
preview.save(PREVIEW)
print(OUT)
print(PREVIEW)
